name: Nest Auth Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Check Code Style
        run: npm run lint

      - name: Build NEST Auth API
        run: npm run build
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DB_CONNECTION_URI: ${{secrets.DB_CONNECTION_URI}}
          ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
          REFRESH_TOKEN_SECRET: ${{secrets.REFRESH_TOKEN_SECRET}}
          SMTP_HOST: ${{secrets.SMTP_HOST}}
          SMTP_PORT: ${{secrets.SMTP_PORT}}
          SMTP_USER: ${{secrets.SMTP_USER}}
          SMTP_PASSWORD: ${{secrets.SMTP_PASSWORD}}
